GET http://localhost:3000/lista

### SEND FETCH LISTA REQUEST

POST http://localhost:3000/lista
Content-Type: application/json

{
    "nombre": "Lista tareas 2"
}

### Editando nombre lista
PUT http://localhost:3000/lista/2
Content-Type: application/json

{
    "nombre": "Lista tareas 2"
}

### Targeta get
GET http://localhost:3000/tarjeta

### Targeta post
POST http://localhost:3000/tarjeta
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmZlbm94QGdtYWlsLmNvbSIsInVzZXJJZCI6MiwidXNlck5vbWJyZSI6Ikx1aXMgRmVybmFuZG8iLCJpYXQiOjE3MzI4MTQ5OTIsImV4cCI6MTczMjkwMTM5Mn0.1o45Y8IAclNZw8ONQBNzg5exUBxoR9bex2K-3Q55kng

{

    "nombre": "Procesar datos 7",
    "descripcion": "",
    "estado":"En proceso",
    "userId": 2,
    "comentarios": []
}

### Editando nombre lista
PUT http://localhost:3000/tarjeta/1
Content-Type: application/json

{
    "estado": "En proceso"
}

### Find SONGS REQUEST
GET http://localhost:3000/songs/1

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE2ODQ5MDkxMTMsImV4cCI6MTY4NDk5NTUxM30.u7vwcccTXkbMIZvg1k0ZOA_dD1TvzZRDbO6xm8w23Bc

{
"title": "Love again",
"artists": [1],
"releasedDate" : "2023-05-11",
"duration" :"02:34",
"lyrics": "Sby, you're my adrenaline. Brought out this other side of me You don't even know Controlling my whole anatomy, oh Fingers are holding you right at the edge You're slipping out of my hands Keeping my secrets all up in my head I'm scared that you won't want me back, oh I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya I wish that I was honest when I had you I shoulda told you that I wanted you for me I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya"
}


### Update SONGS REQUEST
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
"title": "Animals",
"artists": [
    "Martin"
],
"releasedDate" : "2023-02-02",
"duration" :"03:43",
"lyrics": "ANIM, you're my adrenaline. Brought out this other side of me You don't even know Controlling my whole anatomy, oh Fingers are holding you right at the edge You're slipping out of my hands Keeping my secrets all up in my head I'm scared that you won't want me back, oh I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya I wish that I was honest when I had you I shoulda told you that I wanted you for me I dance to every song like it's about ya I drink 'til I kiss someone who looks like ya"
}

### Update SONGS REQUEST
DELETE http://localhost:3000/songs/1


### Create new PlayList

POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "Feel Good Now",
    "songs": [
        6
    ],
    "user": 2
}

### Signup User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "doe",
    "email": "john13@gmail.com",
    "password": "123456"
}

### API KEY JOHN13 TEMP : 17838da8-99a7-443f-89fa-ba7338581ee0

### Signup Artist

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Martin",
    "lastName": "Garrix",
    "email": "martingarrix@gmail.com",
    "password": "123456"
}

### Login Artist

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "marfenox@gmail.com",
    "password": "lufer483"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john12@gmail.com",
    "password": "123456"
}

## Access TOKEN : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4xMkBnbWFpbC5jb20iLCJzdWIiOjEsImlhdCI6MTY4NDg1NTYyMSwiZXhwIjoxNjg0OTQyMDIxfQ.4FAABSVzS_6NUAjldhn7-EZ0UbAUUfKgGZ0Qv4tma7M

### Profile

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmZlbm94QGdtYWlsLmNvbSIsInVzZXJJZCI6MiwidXNlck5vbWJyZSI6Ikx1aXMgRmVybmFuZG8iLCJpYXQiOjE3MzI4MTQ5OTIsImV4cCI6MTczMjkwMTM5Mn0.1o45Y8IAclNZw8ONQBNzg5exUBxoR9bex2K-3Q55kng

### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmZlbm94QGdtYWlsLmNvbSIsInVzZXJJZCI6MiwidXNlck5vbWJyZSI6Ikx1aXMgRmVybmFuZG8iLCJpYXQiOjE3MzI4MTQ5OTIsImV4cCI6MTczMjkwMTM5Mn0.1o45Y8IAclNZw8ONQBNzg5exUBxoR9bex2K-3Q55kng


### Validate 2FA Token
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmZlbm94QGdtYWlsLmNvbSIsInVzZXJJZCI6MiwidXNlck5vbWJyZSI6Ikx1aXMgRmVybmFuZG8iLCJpYXQiOjE3MzI4MTQ5OTIsImV4cCI6MTczMjkwMTM5Mn0.1o45Y8IAclNZw8ONQBNzg5exUBxoR9bex2K-3Q55kng
Content-Type: application/json

{
    "token": "164068"
}

### Disable 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmZlbm94QGdtYWlsLmNvbSIsInVzZXJJZCI6MiwidXNlck5vbWJyZSI6Ikx1aXMgRmVybmFuZG8iLCJpYXQiOjE3MzI4MTQ5OTIsImV4cCI6MTczMjkwMTM5Mn0.1o45Y8IAclNZw8ONQBNzg5exUBxoR9bex2K-3Q55kng


### Access Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer 8b49bdee-84bf-4585-b0f8-f3f23de8b9e9

